import React from 'react';
import { Html5Audio, interpolate, staticFile } from 'remotion';
import { T } from '../theme';

export type VoLine = (typeof T.vo)[number];

const dbToGain = (db: number) => Math.pow(10, db / 20);

/**
 * Music gain under the voice-over: -8 dB, 6-frame (200 ms) attack before each line,
 * 12-frame (400 ms) release after it. Lines closer than the release merge into one duck.
 */
export const duckGain = (frame: number, lines: VoLine[], depthDb = -8) => {
  const floor = dbToGain(depthDb);
  let g = 1;
  for (const l of lines) {
    const a = interpolate(frame, [l.from - 6, l.from, l.to, l.to + 12], [0, 1, 1, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' });
    g = Math.min(g, 1 - (1 - floor) * a);
  }
  return g;
};

/**
 * Music bed + SFX stems (generated by audio/make_score.py from timeline.json) and an
 * optional recorded VO. With a VO present the music ducks under every line; the SFX stem
 * is never ducked so hits and UI ticks stay on their frames.
 *
 * `trimBefore`/`length` play a slice of the master stems — the 9:16 cutdown uses this so its
 * audio is cut from the same mix as the picture.
 */
export const Soundtrack: React.FC<{
  musicSrc?: string;
  sfxSrc?: string;
  voSrc?: string;
  trimBefore?: number;
  length?: number;
  edgeFade?: number; // frames of fade at slice edges (cutdown) to avoid clicks
  gain?: number;
}> = ({ musicSrc = 'audio/music.wav', sfxSrc = 'audio/sfx.wav', voSrc, trimBefore = 0, length, edgeFade = 0, gain = 1 }) => {
  const edge = (f: number) => {
    if (!edgeFade || length === undefined) return 1;
    return Math.min(1, (f + 1) / edgeFade, (length - f) / edgeFade);
  };
  const trim = trimBefore ? { trimBefore, durationInFrames: length } : length !== undefined ? { durationInFrames: length } : {};
  return (
    <>
      <Html5Audio src={staticFile(musicSrc)} {...trim} volume={(f) => gain * edge(f) * (voSrc ? duckGain(f + trimBefore, T.vo) : 1)} />
      <Html5Audio src={staticFile(sfxSrc)} {...trim} volume={(f) => gain * edge(f)} />
      {voSrc && <Html5Audio src={staticFile(voSrc)} {...trim} volume={(f) => gain * edge(f)} />}
    </>
  );
};
