// Sample process catalog for the Overview page. Rows are generated by
// cycling a handful of realistic templates (matching the reference design)
// with varied stats, so search/sort/pagination have a realistic volume
// (120 processes) to work with without fabricating 120 unique concepts.

const PROCESS_TEMPLATES = [
  { title: 'Case Identification & Authorisation', description: 'Analysis of the new requests and suggesting alternates', role: 'Manager', businessUnit: 'Finance' },
  { title: 'Case Identification process', description: 'Analysis of the new requests and suggesting alternates', role: 'Manager', businessUnit: 'Finance' },
  { title: 'Identification process', description: 'Analysis of the new requests and suggesting alternates', role: 'Coordinator', businessUnit: 'Support' },
  { title: 'Utilisation management & analysis', description: 'Analysing the requests and suggesting next steps', role: 'Manager', businessUnit: 'Product' },
  { title: 'Discharge planning', description: 'Detailed plan for discharge of the patient post hospitalisation', role: 'Manager', businessUnit: 'Support' },
  { title: 'Care transition', description: 'Changing the hospitals for a patient based on request', role: 'Support', businessUnit: 'Support' },
  { title: 'Pharmacy selection', description: 'Selecting the pharmacy based on medical records', role: 'Coordinator', businessUnit: 'Finance' },
  { title: 'Claim denial handling', description: 'Reviewing denial reasons and identifying next steps', role: 'Support', businessUnit: 'Finance' },
  { title: 'Claim approval', description: 'Analysing claim denial reasons and suggesting next steps', role: 'Manager', businessUnit: 'Finance' },
  { title: 'Monitoring existing cases', description: 'Reviewing the progress of existing cases', role: 'Coordinator', businessUnit: 'Support' },
  { title: 'Provider network review', description: 'Verifying provider eligibility against the current network', role: 'Analyst', businessUnit: 'Operations' },
  { title: 'Appeals processing', description: 'Handling member appeals against a prior decision', role: 'Specialist', businessUnit: 'Operations' },
];

const ROLE_POOL = [
  'Manager', 'Coordinator', 'Support', 'Analyst', 'Specialist', 'Reviewer',
  'Supervisor', 'Officer', 'Associate', 'Lead', 'Consultant', 'Administrator',
];
const BUSINESS_UNIT_POOL = ['Finance', 'Support', 'Product', 'Operations'];

const TOTAL_PROCESS_COUNT = 120;

function pick(arr, i) { return arr[i % arr.length]; }

function formatMedianDuration(totalSeconds) {
  const m = Math.floor(totalSeconds / 60);
  const s = totalSeconds % 60;
  return `${String(m).padStart(2, '0')}m ${String(s).padStart(2, '0')}s`;
}

function generateProcessCatalog() {
  const rows = [];
  for (let i = 0; i < TOTAL_PROCESS_COUNT; i++) {
    const template = pick(PROCESS_TEMPLATES, i);
    const isTemplateExact = i < PROCESS_TEMPLATES.length;
    rows.push({
      id: `PROC-${1000 + i}`,
      title: template.title,
      description: template.description,
      role: isTemplateExact ? template.role : pick(ROLE_POOL, i * 7 + PROCESS_TEMPLATES.length),
      businessUnit: isTemplateExact ? template.businessUnit : pick(BUSINESS_UNIT_POOL, i * 3 + 1),
      medianDurationSeconds: 300 + ((i * 37) % 900),
      processCount: 40 + ((i * 53) % 220),
      users: 90 + ((i * 131) % 1300),
    });
  }
  return rows;
}
